In [3]:
import pandas as pd
import requests
from io import StringIO

url = "https://en.wikipedia.org/wiki/List_of_top_Premier_League_goal_scorers_by_season"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers, timeout=30)
response.raise_for_status()

tables = pd.read_html(StringIO(response.text))

dfs = []

for df in tables:
    cols = [str(c).strip() for c in df.columns]
    
    if "Season" in cols and "Player" in cols and "Goals" in cols:
        df.columns = cols
        
        club_col = None
        for c in ["Club", "Team"]:
            if c in cols:
                club_col = c
                break
        
        if club_col:
            temp = df[["Season", "Player", club_col, "Goals"]].copy()
            temp = temp.rename(columns={club_col: "Club"})
            dfs.append(temp)

final_df = pd.concat(dfs, ignore_index=True)

final_df["Season"] = final_df["Season"].astype(str).str.strip()
final_df["Player"] = final_df["Player"].astype(str).str.replace(r"\[[^\]]+\]", "", regex=True).str.strip()
final_df["Club"] = final_df["Club"].astype(str).str.replace(r"\[[^\]]+\]", "", regex=True).str.strip()
final_df["Goals"] = final_df["Goals"].astype(str).str.extract(r"(\d+)").astype(int)

final_df.insert(0, "Rank", final_df.groupby("Season")["Goals"].rank(method="min", ascending=False).astype(int))

final_df = final_df[["Rank", "Player", "Club", "Goals", "Season"]]
final_df.to_csv("premier_league_top_scorers.csv", index=False, encoding="utf-8-sig")

print(final_df.head(20))

ValueError: No objects to concatenate

In [ ]:
import pandas as pd
import requests
from io import StringIO

url = "https://en.wikipedia.org/wiki/List_of_top_Premier_League_goal_scorers_by_season"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers, timeout=30)
response.raise_for_status()

tables = pd.read_html(StringIO(response.text))

dfs = []

for df in tables:
    cols = [str(c).strip() for c in df.columns]
    
    if "Season" in cols and "Player" in cols and "Goals" in cols:
        df.columns = cols
        
        club_col = None
        for c in ["Club", "Team"]:
            if c in cols:
                club_col = c
                break
        
        if club_col:
            temp = df[["Season", "Player", club_col, "Goals"]].copy()
            temp = temp.rename(columns={club_col: "Club"})
            dfs.append(temp)

In [6]:
print(len(tables))

36

In [7]:
for i, df in enumerate(tables[:5]):
    print(i, df.shape)
    print(df.head(2))
    print("-" * 40)

0 (13, 4)
   Rank            Player                                   Club  Goals[3]
0     1  Teddy Sheringham  Nottingham Forest / Tottenham Hotspur        22
1     2     Les Ferdinand                    Queens Park Rangers        20
----------------------------------------
1 (12, 4)
   Rank        Player              Club  Goals
0     1     Andy Cole  Newcastle United     34
1     2  Alan Shearer  Blackburn Rovers     31
----------------------------------------
2 (12, 4)
   Rank         Player              Club  Goals
0     1   Alan Shearer  Blackburn Rovers     34
1     2  Robbie Fowler         Liverpool     25
----------------------------------------
3 (11, 4)
   Rank         Player              Club  Goals
0     1   Alan Shearer  Blackburn Rovers     31
1     2  Robbie Fowler         Liverpool     28
----------------------------------------
4 (13, 4)
   Rank        Player              Club  Goals
0     1  Alan Shearer  Newcastle United     25
1     2    Ian Wright           Arsenal     23
----------------------------------------

In [8]:
for i, df in enumerate(tables):
    print(i, list(df.columns))

0 ['Rank', 'Player', 'Club', 'Goals[3]']
1 ['Rank', 'Player', 'Club', 'Goals']
2 ['Rank', 'Player', 'Club', 'Goals']
3 ['Rank', 'Player', 'Club', 'Goals']
4 ['Rank', 'Player', 'Club', 'Goals']
5 ['Rank', 'Player', 'Club', 'Goals']
6 ['Rank', 'Player', 'Club', 'Goals']
7 ['Rank', 'Player', 'Club', 'Goals']
8 ['Rank', 'Player', 'Club', 'Goals']
9 ['Rank', 'Player', 'Club', 'Goals']
10 ['Rank', 'Player', 'Club', 'Goals[4]']
11 ['Rank', 'Player', 'Club', 'Goals[5]']
12 ['Rank', 'Player', 'Team', 'Goals[6]']
13 ['Rank', 'Player', 'Club', 'Goals[7]']
14 ['Rank', 'Player', 'Club', 'Goals[8]']
15 ['Rank', 'Player', 'Club', 'Goals[9]']
16 ['Rank', 'Player', 'Club', 'Goals[10]']
17 ['Rank', 'Player', 'Club', 'Goals[11][12]']
18 ['Rank', 'Player', 'Club', 'Goals[13]']
19 ['Rank', 'Player', 'Club', 'Goals[14]']
20 ['Rank', 'Player', 'Club', 'Goals[15]']
21 ['Rank', 'Player', 'Club', 'Goals[16]']
22 ['Rank', 'Player', 'Club', 'Goals[17]']
23 ['Rank', 'Player', 'Club', 'Goals[18]']
24 ['Rank', 'Player', 'Club', 'Goals']
25 ['Rank', 'Player', 'Club', 'Goals']
26 ['Rank', 'Player', 'Club', 'Goals[19]']
27 ['Rank', 'Player', 'Club', 'Goals[19]']
28 ['Rank', 'Player', 'Club', 'Goals[19]']
29 ['Rank', 'Player', 'Club', 'Goals[19]']
30 ['Rank', 'Player', 'Club', 'Goals[19]']
31 ['Rank', 'Player', 'Club', 'Goals[19]']
32 ['Rank', 'Player', 'Club', 'Goals[19]']
33 ['Rank', 'Player', 'Club', 'Goals[19]']
34 ['vtePremier League', 'vtePremier League.1']
35 [0, 1]

In [9]:
for df in tables:
    df.columns = [str(c).split("[")[0].strip() for c in df.columns]

In [10]:
for i, df in enumerate(tables[:5]):
    print(i, list(df.columns))

0 ['Rank', 'Player', 'Club', 'Goals']
1 ['Rank', 'Player', 'Club', 'Goals']
2 ['Rank', 'Player', 'Club', 'Goals']
3 ['Rank', 'Player', 'Club', 'Goals']
4 ['Rank', 'Player', 'Club', 'Goals']

In [14]:
for df in tables:
    cols = [str(c).split("[")[0].strip() for c in df.columns]
    df.columns = cols

    if "Season" in cols and "Player" in cols and ("Goals" in cols):
        club_col = None
        for c in ["Club", "Team"]:
            if c in cols:
                club_col = c
                break

        if club_col is not None:
            temp = df[["Season", "Player", club_col, "Goals"]].copy()
            temp = temp.rename(columns={club_col: "Club"})
            dfs.append(temp)

In [15]:
if dfs:
    final_df = pd.concat(dfs, ignore_index=True)
else:
    print("dfs is empty")

dfs is empty

In [16]:
dfs = []

for df in tables:
    df = df.copy()
    df.columns = [str(c).split("[")[0].strip() for c in df.columns]
    dfs.append(df)

final_df = pd.concat(dfs, ignore_index=True)

In [17]:
final_df

,Rank,Player,Club,Goals,Team,vtePremier League,vtePremier League.1,0,1
0,1.0,Teddy Sheringham,Nottingham Forest / Tottenham Hotspur,22.0,NaN,NaN,NaN,NaN,NaN
1,2.0,Les Ferdinand,Queens Park Rangers,20.0,NaN,NaN,NaN,NaN,NaN
2,3.0,Dean Holdsworth,Wimbledon F.C.,19.0,NaN,NaN,NaN,NaN,NaN
3,4.0,Micky Quinn,Coventry City,17.0,NaN,NaN,NaN,NaN,NaN
4,5.0,Alan Shearer,Blackburn Rovers,16.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
383,NaN,NaN,NaN,NaN,NaN,Associated competitions,Fantasy Premier League Asia Trophy FA Communit...,NaN,NaN
384,NaN,NaN,NaN,NaN,NaN,Related media,Fever Pitch: The Rise of the Premier League,NaN,NaN
385,NaN,NaN,NaN,NaN,NaN,Category,Category,NaN,NaN
386,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026–27,Arsenal Aston Villa Bournemouth Brentford Brig...
387,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Former,Barnsley Birmingham City Blackburn Rovers Blac...

In [18]:
final_df.to_csv("premier_league_top_scorers.csv", index=False, encoding="utf-8-sig")

In [19]:
import pandas as pd
import requests
from io import StringIO
from bs4 import BeautifulSoup

url = "https://en.wikipedia.org/wiki/List_of_top_Premier_League_goal_scorers_by_season"
headers = {"User-Agent": "Mozilla/5.0"}

response = requests.get(url, headers=headers, timeout=30)
response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")

dfs = []
current_season = None

content = soup.find("div", class_="mw-parser-output")

for element in content.find_all(["h2", "h3", "table"], recursive=False):
    if element.name in ["h2", "h3"]:
        heading = element.get_text(" ", strip=True)
        heading = heading.replace("[edit]", "").strip()

        if "–" in heading or "-" in heading:
            current_season = heading

    elif element.name == "table" and "wikitable" in element.get("class", []):
        df = pd.read_html(StringIO(str(element)))[0]
        df.columns = [str(c).split("[")[0].strip() for c in df.columns]

        if {"Rank", "Player", "Goals"}.issubset(df.columns):
            club_col = "Club" if "Club" in df.columns else "Team" if "Team" in df.columns else None

            if club_col:
                temp = df[["Rank", "Player", club_col, "Goals"]].copy()
                temp = temp.rename(columns={club_col: "Club"})
                temp["Season"] = current_season
                dfs.append(temp)

final_df = pd.concat(dfs, ignore_index=True)
final_df = final_df[["Rank", "Player", "Club", "Goals", "Season"]]

print(final_df.head(20))

    Rank            Player                                   Club  Goals  \
0      1  Teddy Sheringham  Nottingham Forest / Tottenham Hotspur     22
1      2     Les Ferdinand                    Queens Park Rangers     20
2      3   Dean Holdsworth                         Wimbledon F.C.     19
3      4       Micky Quinn                          Coventry City     17
4      5      Alan Shearer                       Blackburn Rovers     16
5      5       David White                        Manchester City     16
6      7   Chris Armstrong                         Crystal Palace     15
7      7      Eric Cantona       Leeds United / Manchester United     15
8      7       Brian Deane                       Sheffield United     15
9      7       Mark Hughes                      Manchester United     15
10     7   Matt Le Tissier                            Southampton     15
11     7       Mark Robins                           Norwich City     15
12     7        Ian Wright                                Arsenal     15
13     1         Andy Cole                       Newcastle United     34
14     2      Alan Shearer                       Blackburn Rovers     31
15     3   Matt Le Tissier                            Southampton     25
16     3      Chris Sutton                           Norwich City     25
17     5        Ian Wright                                Arsenal     23
18     6   Peter Beardsley                       Newcastle United     20
19     7       Mark Bright                    Sheffield Wednesday     19

   Season
0    None
1    None
2    None
3    None
4    None
5    None
6    None
7    None
8    None
9    None
10   None
11   None
12   None
13   None
14   None
15   None
16   None
17   None
18   None
19   None

In [20]:
from bs4 import BeautifulSoup
import pandas as pd
import requests
from io import StringIO

url = "https://en.wikipedia.org/wiki/List_of_top_Premier_League_goal_scorers_by_season"
headers = {"User-Agent": "Mozilla/5.0"}

response = requests.get(url, headers=headers, timeout=30)
response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")
dfs = []

for heading in soup.select("div.mw-heading.mw-heading2 h2"):
    season = heading.get("id")
    if not season:
        continue

    table = heading.find_parent("div").find_next_sibling("table")
    if table is None:
        continue

    df = pd.read_html(StringIO(str(table)))[0]
    df.columns = [str(c).split("[")[0].strip() for c in df.columns]

    if {"Rank", "Player", "Club", "Goals"}.issubset(df.columns):
        df["Season"] = season
        dfs.append(df[["Rank", "Player", "Club", "Goals", "Season"]])

final_df = pd.concat(dfs, ignore_index=True)

In [21]:
final_df

,Rank,Player,Club,Goals,Season
0,1,Teddy Sheringham,Nottingham Forest / Tottenham Hotspur,22,1992–93
1,2,Les Ferdinand,Queens Park Rangers,20,1992–93
2,3,Dean Holdsworth,Wimbledon F.C.,19,1992–93
3,4,Micky Quinn,Coventry City,17,1992–93
4,5,Alan Shearer,Blackburn Rovers,16,1992–93
...,...,...,...,...,...
361,5,João Pedro,Chelsea,15,2025–26
362,7,Dominic Calvert-Lewin,Leeds United,14,2025–26
363,7,Viktor Gyökeres,Arsenal,14,2025–26
364,9,Eli Junior Kroupi,Bournemouth,13,2025–26
365,9,Danny Welbeck,Brighton & Hove Albion,13,2025–26

In [23]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from io import StringIO
import re

url = "https://en.wikipedia.org/wiki/List_of_top_Premier_League_goal_scorers_by_season"
headers = {"User-Agent": "Mozilla/5.0"}

# Step 1: download the page once and save the HTML locally
r = requests.get(url, headers=headers, timeout=30)
r.raise_for_status()
html = r.text
with open("premier_league_scorers_page.html", "w", encoding="utf-8") as f:
    f.write(html)

# Step 2: parse the HTML we just downloaded
soup = BeautifulSoup(html, "html.parser")
dfs = []

# Helper: convert season ids like 1992–93 to 1992/93
# If the id is already a nice season label, it stays as-is.
def season_label(raw):
    raw = str(raw).strip()
    if "–" in raw:
        a, b = raw.split("–", 1)
        return f"{a}/{b}"
    return raw

# Helper: try to extract nationality from the same table row
# by looking for a flag/country-style link in the row HTML.
def extract_nationality_from_row(tr):
    # Common case: a country/flag link in the same row
    # We inspect linked text inside the row and prefer country-like labels.
    country_candidates = []
    for a in tr.find_all("a", href=True):
        txt = a.get_text(" ", strip=True)
        href = a.get("href", "")
        if not txt:
            continue
        # Ignore player links and general wiki links that are not nationality
        if "/wiki/" not in href:
            continue
        # Heuristic: keep short country-like linked text and flag-related labels
        if len(txt) <= 25 and txt.lower() not in {"edit", "[edit]"}:
            country_candidates.append(txt)

    # Prefer obvious country names, otherwise return the first likely country-ish link
    preferred = [
        "England", "Wales", "Scotland", "Northern Ireland", "Ireland",
        "France", "Netherlands", "Germany", "Spain", "Italy", "Brazil",
        "Argentina", "Portugal", "Belgium", "Denmark", "Norway", "Sweden",
        "Ivory Coast", "Nigeria", "Ghana", "Cameroon", "Senegal", "Iceland"
    ]
    for p in preferred:
        if p in country_candidates:
            return p

    # If the row contains a visible flag alt/title/country label, try that too
    for img in tr.find_all("img"):
        alt = img.get("alt", "").strip()
        title = img.get("title", "").strip()
        for val in (alt, title):
            if val and len(val) <= 25:
                return val

    return ""

# Step 3: walk through heading + table pairs
for heading in soup.select("div.mw-heading.mw-heading2 h2"):
    season = season_label(heading.get("id", ""))
    if not season:
        continue

    block = heading.find_parent("div")
    table = block.find_next_sibling("table") if block else None
    if table is None:
        continue

    # Read the scorer table into pandas
    df = pd.read_html(StringIO(str(table)))[0]
    df.columns = [str(c).split("[")[0].strip() for c in df.columns]

    # Keep only the expected scorer-table columns
    if not {"Rank", "Player", "Goals"}.issubset(df.columns):
        continue

    club_col = None
    if "Club" in df.columns:
        club_col = "Club"
    elif "Team" in df.columns:
        club_col = "Team"

    if club_col is None:
        continue

    # Add season and nationality row-by-row using the original HTML row
    rows = table.find_all("tr")
    out_rows = []

    for i, (_, row) in enumerate(df.iterrows(), start=1):
        # Skip header row when matching against HTML rows
        if i >= len(rows):
            break
        tr = rows[i]
        nat = extract_nationality_from_row(tr)
        out_rows.append({
            "Rank": row["Rank"],
            "Player": row["Player"],
            "Club": row[club_col],
            "Goals": row["Goals"],
            "Nationality": nat,
            "Season": season
        })

    if out_rows:
        dfs.append(pd.DataFrame(out_rows))

# Step 4: combine and save
if not dfs:
    raise RuntimeError("No season tables were extracted.")

final_df = pd.concat(dfs, ignore_index=True)
final_df["Goals"] = pd.to_numeric(final_df["Goals"], errors="coerce").astype("Int64")
final_df["Rank"] = pd.to_numeric(final_df["Rank"], errors="coerce").astype("Int64")
final_df.to_csv("premier_league_top_scorers_with_nationality.csv", index=False, encoding="utf-8-sig")

print(final_df.head(20).to_string(index=False))
print("Saved premier_league_top_scorers_with_nationality.csv")

 Rank           Player                                  Club  Goals Nationality  Season
    1 Teddy Sheringham Nottingham Forest / Tottenham Hotspur     22     England 1992/93
    2    Les Ferdinand                   Queens Park Rangers     20     England 1992/93
    3  Dean Holdsworth                        Wimbledon F.C.     19     England 1992/93
    4      Micky Quinn                         Coventry City     17     England 1992/93
    5     Alan Shearer                      Blackburn Rovers     16     England 1992/93
    5      David White                       Manchester City     16     England 1992/93
    7  Chris Armstrong                        Crystal Palace     15     England 1992/93
    7     Eric Cantona      Leeds United / Manchester United     15      France 1992/93
    7      Brian Deane                      Sheffield United     15     England 1992/93
    7      Mark Hughes                     Manchester United     15       Wales 1992/93
    7  Matt Le Tissier                           Southampton     15     England 1992/93
    7      Mark Robins                          Norwich City     15     England 1992/93
    7       Ian Wright                               Arsenal     15     England 1992/93
    1        Andy Cole                      Newcastle United     34     England 1993/94
    2     Alan Shearer                      Blackburn Rovers     31     England 1993/94
    3  Matt Le Tissier                           Southampton     25     England 1993/94
    3     Chris Sutton                          Norwich City     25     England 1993/94
    5       Ian Wright                               Arsenal     23     England 1993/94
    6  Peter Beardsley                      Newcastle United     20     England 1993/94
    7      Mark Bright                   Sheffield Wednesday     19     England 1993/94
Saved premier_league_top_scorers_with_nationality.csv