In [6]:
import pandas as pd
import numpy as np

#!pip install openpyxl

# chnage from scientific notation 
pd.set_option('display.float_format', lambda x: '%.5f' % x)

data = pd.read_csv("premier_league_top_scorers_full.csv") # upload csv

In [7]:
data.columns = data.columns.str.lower().str.replace(" ","_")
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 376 entries, 0 to 375
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   rank         376 non-null    int64
 1   player       376 non-null    str
 2   club         376 non-null    str
 3   goals        376 non-null    int64
 4   nationality  376 non-null    str
 5   season       376 non-null    str
dtypes: int64(2), str(4)
memory usage: 17.8 KB

In [10]:
data.head(5).to_string()

'   rank            player                 club  goals nationality   season\n0     1  Teddy Sheringham    Tottenham Hotspur     22     England  1992/93\n1     2     Les Ferdinand  Queens Park Rangers     20     England  1992/93\n2     3   Dean Holdsworth       Wimbledon F.C.     19     England  1992/93\n3     4       Micky Quinn        Coventry City     17     England  1992/93\n4     5      Alan Shearer     Blackburn Rovers     16     England  1992/93'

In [12]:
# Make sure goals and rank are numeric
data["rank"] = pd.to_numeric(data["rank"], errors="coerce")
data["goals"] = pd.to_numeric(data["goals"], errors="coerce")

In [33]:
player_goals = (
    data.groupby("player", as_index=False)
      .agg(
          total_goals=("goals", "sum"),
          appearances=("season", "count"),
          best_season_goals=("goals", "max")
      )
      .sort_values(["total_goals", "appearances"], ascending=[False, False])
)

player_goals

                player  total_goals  appearances  best_season_goals
0         Alan Shearer          236           10                 34
78          Harry Kane          210            9                 30
127      Mohamed Salah          184            8                 32
171      Thierry Henry          164            7                 30
164      Sergio Agüero          152            7                 26
..                 ...          ...          ...                ...
168     Steve Claridge           12            1                 12
1           Alan Smith           11            1                 11
66    Frédéric Kanouté           11            1                 11
75       Gustavo Poyet           11            1                 11
94   Jonatan Johansson           11            1                 11

[184 rows x 4 columns]

In [34]:
# Find each player's best goal total and the season it happened in
best_season = (
    data.sort_values(["player", "goals", "season"], ascending=[True, False, True])
        .groupby("player", as_index=False)
        .first()[["player", "season", "goals"]]
        .rename(columns={
            "season": "best_season",
            "goals": "best_season_goals"
        })  

)

best_season.sort_values(["best_season_goals", "best_season"], ascending=[False, True ]).head(10)

                player best_season  best_season_goals
60      Erling Haaland     2022/23                 36
9            Andy Cole     1993/94                 34
0         Alan Shearer     1994/95                 34
127      Mohamed Salah     2017/18                 32
30   Cristiano Ronaldo     2007/08                 31
109        Luis Suárez     2013/14                 31
106     Kevin Phillips   1999/2000                 30
171      Thierry Henry     2003/04                 30
156   Robin van Persie     2011/12                 30
78          Harry Kane     2017/18                 30

In [36]:
# join best season to player_scores table
player_goals = player_goals.merge(
    best_season[["player", "best_season"]],
    on="player",
    how="left"
)

player_goals

,player,total_goals,appearances,best_season_goals,best_season
0,Alan Shearer,236,10,34,1994/95
1,Harry Kane,210,9,30,2017/18
2,Mohamed Salah,184,8,32,2017/18
3,Thierry Henry,164,7,30,2003/04
4,Sergio Agüero,152,7,26,2014/15
...,...,...,...,...,...
179,Steve Claridge,12,1,12,1996/97
180,Alan Smith,11,1,11,2000/01
181,Frédéric Kanouté,11,1,11,2000/01
182,Gustavo Poyet,11,1,11,2000/01
183,Jonatan Johansson,11,1,11,2000/01

In [39]:
# Top 10 rows only
top10 = data[data["rank"] <= 10].copy()

player_top10_count = (
    top10.groupby("player", as_index=False)
        .agg(
            top10_appearances=("season", "count"),
            top10_goals=("goals", "sum")
        )
        .sort_values(["top10_appearances", "top10_goals"], ascending=[False, False])
)

player_top10_count

                player  top10_appearances  top10_goals
0         Alan Shearer                 10          236
78          Harry Kane                  9          210
127      Mohamed Salah                  8          184
171      Thierry Henry                  7          164
164      Sergio Agüero                  7          152
..                 ...                ...          ...
168     Steve Claridge                  1           12
1           Alan Smith                  1           11
66    Frédéric Kanouté                  1           11
75       Gustavo Poyet                  1           11
94   Jonatan Johansson                  1           11

[184 rows x 3 columns]

In [41]:
season_summary = (
    data.groupby("season", as_index=False)
         .agg(
             top10_total_goals=("goals", "sum"),
             top10_avg_goals=("goals", "mean"),
             top10_player_count=("player", "count")
         )
         .sort_values("top10_total_goals", ascending=False)
)


season_summary

       season  top10_total_goals  top10_avg_goals  top10_player_count
1     1993/94                261         21.75000                  12
2     1994/95                247         20.58333                  12
26    2018/19                247         16.46667                  15
24    2016/17                230         19.16667                  12
25    2017/18                227         17.46154                  13
0     1992/93                215         16.53846                  13
17    2009/10                215         19.54545                  11
30    2022/23                213         19.36364                  11
31    2023/24                210         19.09091                  11
4     1996/97                207         15.92308                  13
32    2024/25                207         18.81818                  11
3     1995/96                205         18.63636                  11
8     2000/01                202         14.42857                  14
19    2011/12                202         18.36364                  11
10    2002/03                199         18.09091                  11
27    2019/20                193         19.30000                  10
22    2014/15                192         16.00000                  12
11    2003/04                187         18.70000                  10
7   1999/2000                186         18.60000                  10
9     2001/02                185         18.50000                  10
15    2007/08                185         18.50000                  10
20    2012/13                184         18.40000                  10
21    2013/14                184         18.40000                  10
23    2015/16                180         18.00000                  10
13    2005/06                178         16.18182                  11
29    2021/22                169         16.90000                  10
28    2020/21                168         16.80000                  10
18    2010/11                168         15.27273                  11
33    2025/26                166         16.60000                  10
5     1997/98                159         15.90000                  10
6     1998/99                159         15.90000                  10
16    2008/09                153         13.90909                  11
12    2004/05                148         14.80000                  10
14    2006/07                145         14.50000                  10

In [44]:
highest_scoring_season = season_summary.iloc[0]
lowest_scoring_season = season_summary.iloc[-1]

print(f"Highest scoring season: {highest_scoring_season['season']} with {highest_scoring_season['top10_total_goals']} goals")
print(f"Lowest scoring season: {lowest_scoring_season['season']} with {lowest_scoring_season['top10_total_goals']} goals")

Highest scoring season: 1993/94 with 261 goals
Lowest scoring season: 2006/07 with 145 goals

In [45]:
club_summary = (
    data.groupby("club", as_index=False)
         .agg(
             total_top10_goals=("goals", "sum"),
             top10_appearances=("player", "count"),
             unique_players=("player", "nunique")
         )
         .sort_values(["total_top10_goals", "top10_appearances"], ascending=[False, False])
)

club_summary

,club,total_top10_goals,top10_appearances,unique_players
22,Manchester United,741,41,21
20,Liverpool,700,37,13
0,Arsenal,675,37,16
21,Manchester City,600,32,17
35,Tottenham Hotspur,569,31,14
11,Chelsea,418,25,12
24,Newcastle United,338,17,9
1,Aston Villa,260,17,10
4,Blackburn Rovers,224,11,7
32,Southampton,210,13,8
18,Leeds United,163,10,8
15,Everton,160,10,8
19,Leicester City,156,9,3
33,Sunderland,112,6,4
23,Middlesbrough,107,8,7
13,Crystal Palace,95,6,5
8,Brentford,81,4,4
7,Bournemouth,79,5,5
28,Queens Park Rangers,78,4,2
12,Coventry City,76,5,3
38,West Ham United,72,5,5
42,Wolverhampton Wanderers,59,4,3
16,Fulham,58,4,4
26,Nottingham Forest,57,3,3
25,Norwich City,55,3,3
34,Swansea City,49,3,3
37,West Bromwich Albion,46,3,3
27,Portsmouth,44,3,2
10,Charlton Athletic,42,3,2
9,Brighton & Hove Albion,38,3,2
36,Watford,28,2,2
17,Ipswich Town,19,1,1
31,Sheffield Wednesday,19,1,1
41,Wimbledon F.C.,19,1,1
2,Birmingham City,17,1,1
3,Blackburn,17,1,1
40,Wimbledon,17,1,1
30,Sheffield United,15,1,1
5,Blackpool,13,1,1
14,Derby County,13,1,1
29,Reading,13,1,1
6,Bolton Wanderers,12,1,1
39,Wigan Athletic,12,1,1

In [46]:
nationality_summary = (
    top10.groupby("nationality", as_index=False)
         .agg(
             total_top10_goals=("goals", "sum"),
             top10_appearances=("player", "count"),
             unique_players=("player", "nunique")
         )
         .sort_values(["total_top10_goals", "top10_appearances"], ascending=[False, False])
)

print("\nNationalities with the most top 10 goals / appearances:")
print(nationality_summary.head(20).to_string(index=False))

Nationalities with the most top 10 goals / appearances:
        nationality  total_top10_goals  top10_appearances  unique_players
            England               2890                163              68
             France                511                 30              12
        Netherlands                334                 18               6
             Norway                219                 11               7
            Belgium                211                 13               4
          Argentina                209                 10               2
              Egypt                184                  8               1
              Spain                156                  9               6
             Brazil                134                  9               9
           Portugal                117                  6               3
            Nigeria                116                  8               3
            Senegal                112                  7               4
        Ivory Coast                111                  6               4
              Wales                 79                  5               5
             Sweden                 75                  4               3
Trinidad and Tobago                 72                  4               1
              Italy                 71                  5               5
        South Korea                 69                  4               1
          Australia                 65                  4               2
            Uruguay                 65                  3               2

In [ ]:
nationality_players = (
    data.sort_values(["nationality", "goals"], ascending=[True, False])
        .groupby("nationality", as_index=False)
        .agg(
            total_top10_goals=("goals", "sum"),
            top10_appearances=("player", "count"),
            unique_players=("player", "nunique"),
            players=("player", lambda x: ", ".join(x))
        )
        .sort_values(["total_top10_goals", "top10_appearances"], ascending=[False, False])
)


print(nationality_players.head(20).to_string(index=False))

           nationality                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          players
               Algeria                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     [Riyad Mahrez, Riyad Mahrez]
             Argentina                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              [Sergio Agüero, Sergio Agüero, Carlos Tevez, Sergio Agüero, Sergio Agüero, Sergio Agüero, Carlos Tevez, Sergio Agüero, Sergio Agüero, Carlos Tevez]
             Australia                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            [Mark Viduka, Mark Viduka, Harry Kewell, Mark Viduka]
               Belgium                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        [Romelu Lukaku, Christian Benteke, Romelu Lukaku, Romelu Lukaku, Eden Hazard, Romelu Lukaku, Eden Hazard, Romelu Lukaku, Christian Benteke, Kevin De Bruyne, Eden Hazard, Christian Benteke, Eden Hazard]
Bosnia and Herzegovina                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         [Edin Džeko, Edin Džeko]
                Brazil                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      [Igor Thiago, Roberto Firmino, Gabriel Martinelli, Matheus Cunha, João Pedro, Robinho, Gabriel Jesus, Richarlison, Juninho]
              Bulgaria                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         [Dimitar Berbatov, Dimitar Berbatov, Dimitar Berbatov, Dimitar Berbatov]
               Burundi                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 [Saido Berahino]
              Cameroon                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   [Bryan Mbeumo]
                 Chile                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 [Alexis Sánchez, Alexis Sánchez, Alexis Sánchez]
              Colombia                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              [Juan Pablo Ángel, Hamilton Ricard]
            Costa Rica                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 [Paulo Wanchope]

In [48]:
for _, row in nationality_players.iterrows():
    print(f"\n{row['nationality']} ({row['total_top10_goals']} goals)")
    print(row["players"])

England (2890 goals)
Andy Cole, Alan Shearer, Alan Shearer, Alan Shearer, Kevin Phillips, Harry Kane, Harry Kane, Harry Kane, Robbie Fowler, Wayne Rooney, Wayne Rooney, Matt Le Tissier, Chris Sutton, Robbie Fowler, Les Ferdinand, Alan Shearer, Harry Kane, Les Ferdinand, Darren Bent, Jamie Vardy, Ian Wright, Ian Wright, Alan Shearer, Alan Shearer, James Beattie, Jamie Vardy, Harry Kane, Teddy Sheringham, Stan Collymore, Alan Shearer, Frank Lampard, Danny Ings, Cole Palmer, Andy Cole, Andy Johnson, Daniel Sturridge, Harry Kane, Les Ferdinand, Peter Beardsley, Jamie Vardy, Raheem Sterling, Ivan Toney, Dean Holdsworth, Mark Bright, Matt Le Tissier, Michael Bridges, Andy Cole, Marcus Stewart, Michael Owen, Michael Owen, Phil Foden, Dominic Solanke, Ollie Watkins, Teddy Sheringham, Ian Wright, Robbie Fowler, Dion Dublin, Michael Owen, Chris Sutton, Michael Owen, Darren Bent, Jermain Defoe, Charlie Austin, Dele Alli, Raheem Sterling, Jamie Vardy, Harry Kane, Callum Wilson, Micky Quinn, Dean Holdsworth, Rod Wallace, Andy Cole, Alan Shearer, Darren Bent, Wayne Rooney, Harry Kane, Raheem Sterling, Marcus Rashford, Patrick Bamford, Harry Kane, Marcus Rashford, Alan Shearer, David White, Tony Cottee, Les Ferdinand, Teddy Sheringham, Les Ferdinand, Michael Owen, Michael Owen, Frank Lampard, Wayne Rooney, Steven Gerrard, Dominic Calvert-Lewin, Jarrod Bowen, Bukayo Saka, Ollie Watkins, Ollie Watkins, Chris Armstrong, Brian Deane, Matt Le Tissier, Mark Robins, Ian Wright, Chris Sutton, Chris Armstrong, Ian Wright, Andy Cole, Teddy Sheringham, Robbie Fowler, Grant Holt, Rickie Lambert, Frank Lampard, Jay Rodriguez, Jermain Defoe, Jermain Defoe, Jamie Vardy, Jamie Vardy, Ollie Watkins, Cole Palmer, Morgan Gibbs-White, Stan Collymore, Dion Dublin, Darren Huckerby, Dion Dublin, Robbie Fowler, Julian Joachim, Alan Shearer, Chris Armstrong, Emile Heskey, Kevin Phillips, Paul Scholes, James Beattie, Marlon Harewood, Wayne Rooney, Callum Wilson, Ollie Watkins, Bukayo Saka, Dominic Calvert-Lewin, Dion Dublin, Matt Le Tissier, Andy Cole, Jermain Defoe, Frank Lampard, Darren Bent, Gabriel Agbonlahor, DJ Campbell, Andy Carroll, Troy Deeney, Glenn Murray, Raheem Sterling, Danny Welbeck, Steve Claridge, Stan Collymore, Andy Cole, Peter Crouch, Gabriel Agbonlahor, Darren Bent, Kevin Davies, Frank Lampard, Wayne Rooney, Wayne Rooney, Glenn Murray, James Beattie, Alan Smith

France (511 goals)
Thierry Henry, Thierry Henry, Thierry Henry, Thierry Henry, Thierry Henry, Louis Saha, Nicolas Anelka, Eric Cantona, Nicolas Anelka, Thierry Henry, Thierry Henry, Anthony Martial, Nicolas Anelka, Olivier Giroud, Olivier Giroud, Jean-Philippe Mateta, Eric Cantona, Nicolas Anelka, Eric Cantona, Robert Pires, Robert Pires, Olivier Giroud, Alexandre Lacazette, Jean-Philippe Mateta, Louis Saha, Florent Malouda, Alexandre Lacazette, Paul Pogba, Alexandre Lacazette, Eli Junior Kroupi

Netherlands (334 goals)
Robin van Persie, Robin van Persie, Ruud van Nistelrooy, Jimmy Floyd Hasselbaink, Jimmy Floyd Hasselbaink, Ruud van Nistelrooy, Ruud van Nistelrooy, Ruud van Nistelrooy, Jimmy Floyd Hasselbaink, Robin van Persie, Dennis Bergkamp, Jimmy Floyd Hasselbaink, Jimmy Floyd Hasselbaink, Dirk Kuyt, Rafael van der Vaart, Dennis Bergkamp, Dirk Kuyt, Dirk Kuyt

Norway (219 goals)
Erling Haaland, Erling Haaland, Erling Haaland, Erling Haaland, Ole Gunnar Solskjær, Ole Gunnar Solskjær, Joshua King, Martin Ødegaard, Steffen Iversen, Jørgen Strand Larsen, John Carew

Belgium (211 goals)
Romelu Lukaku, Christian Benteke, Romelu Lukaku, Romelu Lukaku, Eden Hazard, Romelu Lukaku, Eden Hazard, Romelu Lukaku, Christian Benteke, Kevin De Bruyne, Eden Hazard, Christian Benteke, Eden Hazard

Argentina (209 goals)
Sergio Agüero, Sergio Agüero, Carlos Tevez, Sergio Agüero, Sergio Agüero, Sergio Agüero, Carlos Tevez, Sergio Agüero, Sergio Agüero, Carlos Tevez

Egypt (184 goals)
Mohamed Salah, Mohamed Salah, Mohamed Salah, Mohamed Salah, Mohamed Salah, Mohamed Salah, Mohamed Salah, Mohamed Salah

Spain (156 goals)
Fernando Torres, Diego Costa, Diego Costa, Fernando Torres, Michu, Cesc Fàbregas, Fernando Llorente, Fernando Torres, David Silva

Brazil (134 goals)
Igor Thiago, Roberto Firmino, Gabriel Martinelli, Matheus Cunha, João Pedro, Robinho, Gabriel Jesus, Richarlison, Juninho

Portugal (117 goals)
Cristiano Ronaldo, Cristiano Ronaldo, Bruno Fernandes, Cristiano Ronaldo, Cristiano Ronaldo, Diogo Jota

Nigeria (116 goals)
Yakubu, Yakubu, Yakubu, Peter Odemwingie, Odion Ighalo, Yakubu, Yakubu, Yakubu

Senegal (112 goals)
Sadio Mané, Sadio Mané, Demba Ba, Sadio Mané, Demba Ba, Papiss Cissé, Henri Camara

Ivory Coast (111 goals)
Didier Drogba, Didier Drogba, Yaya Touré, Wilfried Bony, Wilfried Zaha, Didier Drogba

Wales (79 goals)
Gareth Bale, Mark Hughes, Dean Saunders, John Hartson, Craig Bellamy

Sweden (75 goals)
Alexander Isak, Alexander Isak, Zlatan Ibrahimović, Viktor Gyökeres

Trinidad and Tobago (72 goals)
Dwight Yorke, Dwight Yorke, Dwight Yorke, Dwight Yorke

Italy (71 goals)
Fabrizio Ravanelli, Paolo Di Canio, Gianfranco Zola, Mario Balotelli, Graziano Pellè

South Korea (69 goals)
Son Heung-min, Son Heung-min, Son Heung-min, Son Heung-min

Australia (65 goals)
Mark Viduka, Mark Viduka, Harry Kewell, Mark Viduka

Uruguay (65 goals)
Luis Suárez, Luis Suárez, Gustavo Poyet

Bulgaria (62 goals)
Dimitar Berbatov, Dimitar Berbatov, Dimitar Berbatov, Dimitar Berbatov

Republic of Ireland (58 goals)
Robbie Keane, Robbie Keane, Niall Quinn, Kevin Doyle

Togo (55 goals)
Emmanuel Adebayor, Emmanuel Adebayor, Emmanuel Adebayor

Chile (53 goals)
Alexis Sánchez, Alexis Sánchez, Alexis Sánchez

Germany (49 goals)
Jürgen Klinsmann, Uwe Rösler, İlkay Gündoğan

Gabon (44 goals)
Pierre-Emerick Aubameyang, Pierre-Emerick Aubameyang

Mexico (43 goals)
Raúl Jiménez, Javier Hernández, Raúl Jiménez

Iceland (39 goals)
Eiður Guðjohnsen, Gylfi Sigurðsson, Eiður Guðjohnsen

Colombia (31 goals)
Juan Pablo Ángel, Hamilton Ricard

Bosnia and Herzegovina (30 goals)
Edin Džeko, Edin Džeko

Algeria (29 goals)
Riyad Mahrez, Riyad Mahrez

Finland (28 goals)
Mikael Forssell, Jonatan Johansson

Cameroon (20 goals)
Bryan Mbeumo

New Zealand (20 goals)
Chris Wood

DR Congo (19 goals)
Yoane Wissa

Paraguay (19 goals)
Roque Santa Cruz

South Africa (18 goals)
Benni McCarthy

Ghana (17 goals)
Antoine Semenyo

United States (17 goals)
Clint Dempsey

Russia (16 goals)
Andrei Kanchelskis

Scotland (16 goals)
Kevin Gallacher

Zimbabwe (15 goals)
Benjani

Burundi (14 goals)
Saido Berahino

Latvia (14 goals)
Marians Pahars

Serbia (14 goals)
Aleksandar Mitrović

Costa Rica (13 goals)
Paulo Wanchope

Croatia (12 goals)
Alen Bokšić

Mali (11 goals)
Frédéric Kanouté

In [50]:
with pd.ExcelWriter("premier_league_summaries.xlsx", engine="openpyxl") as writer:
    player_goals.to_excel(writer, sheet_name="player_goals", index=False)
    player_top10_count.to_excel(writer, sheet_name="top10_counts", index=False)
    season_summary.to_excel(writer, sheet_name="season_summary", index=False)
    club_summary.to_excel(writer, sheet_name="club_summary", index=False)
    nationality_summary.to_excel(writer, sheet_name="nationality_summary", index=False)